### ISSUE TITLE
Recuperation de l'amcache

### ISSUE THREAD

**Issue by ghost** [Crypt-0n/C0-FF-EE#4]
Pour recuperation et formatage en texte "brut" des données de l'Amcache.

W7 : 
C:\Windows\AppCompat\Programs\RecentFileCache.bcf
C:\Windows\AppCompat\Programs\AEINV_WER_{GUID}_YYYYMMDD_hhmm.xml

W8:
C:\Windows\AppCompat\Programs\AmCache.hve
C:\Windows\AppCompat\Programs\AEINV_AMI_WER_{GUID}_YYYYMMDD_hhmm.xml
C:\Windows\AppCompat\Programs\DevInvCache\PropCache.bin

W10
C:\Windows\AppCompat\Programs\AmCache.hve

---
https://www.ssi.gouv.fr/agence/publication/analyse-de-lamcache/

**Comment by jlequen** [comment]
Pour ajout de l'outil https://github.com/EricZimmerman/AmcacheParser

**Comment by jlequen** [comment]
Récupération de l'amcache ajoutée, mais pas testée sur Windows 7
